### ISSUE TITLE
Wiki not updated

### ISSUE THREAD

**Issue by AbuBaniaz** [LraiZer/AutoBouquetsWiki#5]
Greetings
I got a PM from @jimbo2018 saying that the wiki has not been updated. Can you please have a look when you get a chance?

Also, can we remove `www.ukcvs.net` link from the bottom of the page since it has been taken over.

**Comment by LraiZer** [comment]
Wiki looks to have auto updated ok for past three days just fine, it appears up to date.

Only one missing archive page from 1st August due to an overnight power cut caused by lightning strike. This also has now been uploaded manually.

http://commando.org.uk/wiki/bskyb/updates/2024/08/wiki-updates-2024-08-01-0600.html

**Comment by jimbo2018** [comment]
Yes all working at present. Thank you.

**Comment by jimbo2018** [comment]
Hi.
 
The AutobouquetsWiki did not update on 12 September. 
 
I hope you can fix this soon 
 
Thanks
 
James

**Comment by jimbo2018** [comment]
Hi.
 
Both scans on autobouquets wiki failed on 11 November.
 
Hope you can fix it soon 
 
Cheers
James

**Comment by jimbo2018** [comment]
Oops.
 
Sorry my mistake. I keep thinking today is 11 November and you know why. All is normal as it did update correctly on 10th.sorry
